//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinicHistory_Alergie
    {
        public int id { get; set; }
        public int clinicHistoryId { get; set; }
        public int AlergieId { get; set; }
    
        public virtual alergy alergy { get; set; }
        public virtual clinicHistory clinicHistory { get; set; }
    }
}
